### ISSUE TITLE
ckg model to much?

### ISSUE THREAD

**Issue by av8dtop** [p1atdev/stable-journey-bot#11]
Task start deno run -A main.ts
[INFO] Commands: [ "imagine", "switch", "info", "status", "refresh" ]
[INFO] Registered handling interactions
[INFO] Registering commands globally
[ERROR] Error occurred when setting up bot: Error: [400] The options was improperly formatted, or the server couldn't understand it.
{"code":50035,"errors":{"0":{"options":{"2":{"choices":{"_errors":[{"code":"BASE_TYPE_MAX_LENGTH","message":"Must be 25 or fewer in length."}]}}}}},"message":"Invalid Form Body"}
    at Object.runMethod (https://deno.land/x/discordeno@18.0.1/rest/runMethod.ts:30:9)
    at upsertGlobalApplicationCommands (https://deno.land/x/discordeno@18.0.1/helpers/interactions/commands/upsertGlobalApplicationCommands.ts:24:34)
    at Object.converted.<computed> [as upsertGlobalApplicationCommands] (https://deno.land/x/discordeno@18.0.1/bot.ts:402:7)
    at registerCommands (file:///C:/stable-journey-bot/commands.ts:46:27)
    at refreshCommands (file:///C:/stable-journey-bot/utils.ts:32:19)
    at async StableJourneyBot.setup (file:///C:/stable-journey-bot/bot.ts:21:13)
    at async StableJourneyBot.start (file:///C:/stable-journey-bot/bot.ts:34:9)
    at async file:///C:/stable-journey-bot/main.ts:8:1
[ERROR] Please check your config file or server status and try again!

**Comment by av8dtop** [comment]
I have encountered a problem, the repeated command cannot be registered, can you help me solve it?
