### ISSUE TITLE
The Authorization token you passed did not have permission

### ISSUE THREAD

**Issue by yamosin** [p1atdev/stable-journey-bot#6]
```
PS D:\stable-journey-bot> deno task start
Task start deno run -A main.ts
[SUCCESS] Successfully connected to gateway
error: Uncaught (in promise) Error: [403] The Authorization token you passed did not have permission to the resource.
{"message":"Missing Access","code":50001}
  Error.captureStackTrace(errorStack);
        ^
    at Object.runMethod (https://deno.land/x/discordeno@17.1.0/rest/runMethod.ts:30:9)
    at getGuildApplicationCommands (https://deno.land/x/discordeno@17.1.0/helpers/interactions/commands/getGuildApplicationCommands.ts:20:34)
    at Object.converted.<computed> [as getGuildApplicationCommands] (https://deno.land/x/discordeno@17.1.0/bot.ts:401:7)
    at registerCommands (file:///D:/stable-journey-bot/command.ts:143:29)
    at StableJourneyBot.refreshCommands (file:///D:/stable-journey-bot/bot.ts:50:15)
    at async Object.bot.events.ready (file:///D:/stable-journey-bot/bot.ts:62:13)
```

I already give bot a adminisitor permission and another SD discord bot can work with same token

**Comment by yamosin** [comment]
Well I figured it out
It requires the exact Guild ID, not the channel ID, the other bot only needs the token to use, even if the channel ID is used in the Guild ID option it won't affect the use
